spring:
  application:
    name: ribbon-client
server:
  port: 2525
  
shoppinglist-product-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9932,localhost:9923
    ServerListRefreshInterval: 15000  
    
customer-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:1823,localhost:1832
    ServerListRefreshInterval: 15000  
    
hystrix:
  dashboard:
    enable-ignore-connection-close-header: true

management:
  endpoints:
    web:
      exposure:
        include: "*" 
 